---

# OS.

- name: Nginx repo key
  apt_key:
      url: https://nginx.org/keys/nginx_signing.key
      state: present

- name: Nginx repo
  apt_repository:
      repo: deb http://nginx.org/packages/debian buster nginx
      state: present

- name: Packages
  apt:
      pkg:
          - certbot
          - nginx


- name: Default HTTP server
  notify:
      - restart nginx service
  template:
      src: default.conf
      dest: /etc/nginx/conf.d/default.conf


# Certbot.

- name: Webroot
  file:
      path: "{{ letsencrypt_webroot }}"
      state: directory
      owner: nginx
      group: nginx
      mode: 0755

- name: Stat
  stat:
      path: "/etc/letsencrypt/live/{{ hostname }}"
  register: remote_cert_dir
  # Hook
  # Notify

# Configure the renewal script when cert exists.
- name: Hook
  template:
      src: hook
      dest: /etc/letsencrypt/renewal-hooks/deploy/nginx
      mode: 0700
  when: remote_cert_dir.stat.exists

# Run certbot when cert doesn't exist.
- name: Notify
  notify:
      - run certbot
  command: /bin/true
  when: not remote_cert_dir.stat.exists


# Handlers.

- name: Handlers
  meta: flush_handlers
