---

# Basic stuff.

- name: Hostname
  notify:
      - notify reboot
  hostname:
      name: "{{ hostname }}"

- name: Timezone
  notify:
      - notify reboot
  timezone:
      name: "{{ timezone }}"
  when: timezone != ""


# SSH port.

- name: Revert SSH port
  notify:
      - notify restart sshd
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^Port "
      state: absent
  when: ssh_port == "22"

- name: Change SSH port
  notify:
      - notify restart sshd
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^Port "
      line: "Port {{ ssh_port }}"
      insertafter: "^#Port "
  when: ssh_port != "22"


# OS update.

- name: Update
  apt:
      update-cache: true

- name: Upgrade
  apt:
      upgrade: full

- name: Stat reboot
  stat:
      path: /var/run/reboot-required
  register: reboot_required

- name: Notify handler
  notify:
      - notify reboot
  command: /bin/true
  when: reboot_required.stat.exists


# Handlers.

- name: Handlers
  meta: flush_handlers
