---
- name: Deploy stack
  hosts: localhost
  become: false
  gather_facts: false
  vars:

      ipset_repo: https://github.com/tessercat/firewall-ipset.git
      ipset_version: master

      firewall_api_repo: https://github.com/puptel/firewall-api.git
      firewall_api_version: master

  roles:
      - {role: exim, tags: [exim]}
      - {role: host, tags: [host]}
      - {role: nginx, tags: [nginx]}
      - {role: ipset, tags: [ipset, firewall]}
      - {role: iptables, tags: [iptables, firewall]}
        # - {role: firewall, tags: [firewall]}
        # - {role: dev, tags: [dev]}
