---
- name: Deploy stack
  hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:

      ipset_repo: https://github.com/tessercat/firewall-ipset.git
      ipset_version: master

      firewall_repo: https://github.com/tessercat/firewall-api.git
      firewall_version: master

      prometheus_version: 2.21.0
      alertmanager_version: 0.21.0
      node_exporter_version: 1.0.1

  roles:
      - {role: exim, tags: [exim]}
      - {role: host, tags: [host]}
      - {role: nginx, tags: [nginx]}
      - {role: firewall/ipset, tags: [ipset, firewall]}
      - {role: firewall/iptables, tags: [iptables, firewall]}
      - {role: firewall/api, tags: [firewall-api, firewall]}
      - {role: metrics/node_exporter, tags: [node_exporter, metrics]}
      - {role: metrics/prometheus, tags: [prometheus, metrics]}
      - {role: metrics/alertmanager, tags: [alertmanager, metrics]}
