---
- name: Restart service
  listen:
      - restart firewall service
  systemd:
      name: firewall.service
      state: restarted

- name: Restart clean timer
  listen:
      - restart ipset-clean timer
  systemd:
      name: ipset-clean.timer
      state: restarted

- name: Restart nginx service
  listen:
      - restart nginx service
  systemd:
      name: nginx.service
      state: restarted
