---

# OS.

- name: Packages
  apt:
      pkg:
          - ipset


# Sets.

- name: Directory
  file:
      path: /opt/ipset
      state: directory
      mode: 0700

- name: Subdirectories
  file:
      path: item
      state: directory
  with_items:
      - /opt/ipset/sets
      - /opt/ipset/lists

- name: Sets
  notify:
      - reload ipset service
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  loop:
      - {src: "blacklist4", dest: "/opt/ipset/sets/blacklist4"}
      - {src: "blacklist6", dest: "/opt/ipset/sets/blacklist6"}
      - {src: "whitelist4", dest: "/opt/ipset/sets/whitelist4"}
      - {src: "whitelist6", dest: "/opt/ipset/sets/whitelist6"}

- name: Script
  copy:
      src: script.bash
      dest: /opt/ipset/load.bash

- name: Service
  copy:
      src: service
      dest: /etc/systemd/system/ipset.service
      mode: 0644

- name: Service status
  systemd:
      name: ipset.service
      enabled: true
      daemon-reload: true


# Handlers.

- name: Handlers
  meta: flush_handlers
