---
# OS.

- name: User
  ansible.builtin.user:
      name: node_exporter
      system: true
      shell: /usr/sbin/nologin

- name: Metrics directory
  ansible.builtin.file:
      path: /opt/metrics
      state: directory
      mode: "0755"

- name: Directory
  ansible.builtin.file:
      path: /opt/metrics/node_exporter
      state: directory
      mode: "0700"
      owner: node_exporter
      group: node_exporter


# Download and install node_exporter.

- name: Stat archive
  ansible.builtin.stat:
      path: "/opt/metrics/node_exporter/\
             node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  register: node_archive
  # Download

- name: Download
  ansible.builtin.get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/\
            v{{ node_exporter_version }}/\
            node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: /opt/metrics/node_exporter
      mode: "0644"
  when: not node_archive.stat.exists
  register: node_download
  # Clean

- name: Clean
  ansible.builtin.file:
      path: /opt/metrics/node_exporter/bin
      state: absent
  when: node_download is changed  # noqa: no-handler

- name: Stat bin
  ansible.builtin.stat:
      path: /opt/metrics/node_exporter/bin
  register: node_bin
  # Unarchive
  # Move

- name: Unarchive
  ansible.builtin.unarchive:
      src: "/opt/metrics/node_exporter/\
            node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: /opt/metrics/node_exporter
      remote_src: true
      owner: node_exporter
      group: node_exporter
  when: not node_bin.stat.exists

- name: Move
  notify:
      - restart node exporter service
  ansible.builtin.command:
      cmd: "mv /opt/metrics/node_exporter/\
            node_exporter-{{ node_exporter_version }}.linux-amd64 \
            /opt/metrics/node_exporter/bin"
  when: not node_bin.stat.exists
  changed_when: true

- name: Service
  notify:
      - restart node exporter service
  ansible.builtin.template:
      src: service
      dest: /etc/systemd/system/node_exporter.service
      mode: "0644"

- name: Service status
  ansible.builtin.systemd:
      name: node_exporter.service
      enabled: true
      daemon-reload: true


# Handlers.

- name: Handlers
  ansible.builtin.meta: flush_handlers
