---
# OS.

- name: User
  user:
      name: alertmanager
      system: true
      shell: /usr/sbin/nologin

- name: Metrics directory
  file:
      path: /opt/metrics
      state: directory

- name: Directory
  file:
      path: /opt/metrics/alertmanager
      state: directory
      mode: 0700
      owner: alertmanager
      group: alertmanager


# Download and install.

- name: Stat archive
  stat:
      path: "/opt/metrics/alertmanager/\
             alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
  register: alert_archive
  # Download

- name: Download
  get_url:
      url: "https://github.com/prometheus/alertmanager/releases/download/\
            v{{ alertmanager_version }}/\
            alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
      dest: /opt/metrics/alertmanager
  when: not alert_archive.stat.exists
  register: alert_download
  # Clean

- name: Clean
  file:
      path: /opt/metrics/alertmanager/bin
      state: absent
  when: alert_download is changed

- name: Stat bin
  stat:
      path: /opt/metrics/alertmanager/bin
  register: alert_bin
  # Unarchive
  # Install

- name: Unarchive
  unarchive:
      src: "/opt/metrics/alertmanager/\
            alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
      dest: /opt/metrics/alertmanager
      remote_src: true
      owner: alertmanager
      group: alertmanager
  when: not alert_bin.stat.exists

- name: Move
  command: "mv /opt/metrics/alertmanager/\
            alertmanager-{{ alertmanager_version }}.linux-amd64 \
            /opt/metrics/alertmanager/bin"
  when: not alert_bin.stat.exists
  register: alert_install
  # Notify

- name: Notify
  notify:
      - restart alertmanager service
  command: /bin/true
  when: alert_install is changed

- name: Config
  notify:
      - restart alertmanager service
  template:
      src: alertmanager.yml
      dest: /opt/metrics/alertmanager/alertmanager.yml
      owner: alertmanager
      group: alertmanager


# Service.

- name: Service
  notify:
      - restart alertmanager service
  template:
      src: service
      dest: /etc/systemd/system/alertmanager.service

- name: Service status
  systemd:
      name: alertmanager.service
      enabled: true
      daemon-reload: true


# Handlers.

- name: Handlers
  meta: flush_handlers
