---
global:
  external_labels:
    hostname: '{{ hostname }}'
rule_files:
  - '/opt/metrics/prometheus/rules.yml'
alerting:
  alertmanagers:
    - path_prefix: '/metrics/alertmanager'
      static_configs:
        - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
