---
- name: Restart sshd service
  listen:
      - notify restart sshd
  ansible.builtin.systemd:
      name: sshd.service
      state: restarted

- name: Mail admin
  listen:
      - notify reboot
  community.general.mail:
      to: "<{{ admin_email }}>"
      from: "noreply@{{ hostname }}"
      subject: "[{{ hostname }}] Reboot required"
      body: "Host configuration or packages on {{ hostname }} have \
             changed and a reboot is required."
      secure: never
