#!/bin/bash
# Sync save files with the sets in memory.
# Copyright (c) 2018 Peter Christensen, MIT License.
IPSET_BIN=/sbin/ipset
IPSET_DIR=/opt/ipsets/sets
IPSET_FILES=($(cd $IPSET_DIR; ls)) # IP set save files.
IPSET_SETS=($($IPSET_BIN list -name)) # IP sets in memory.

contains() {
    local elem match="$1"
    shift
    for elem; do
        [[ "$elem" == "$match" ]] && return 0
    done
    return 1
}

# If a set in memory has a save file, flush the set, but run only add
# commands. Otherise run all commands.
for ipset in ${IPSET_FILES[@]}; do
    contains $ipset ${IPSET_SETS[@]}
    if [ $? -eq 0 ]; then
        temp=$IPSET_DIR/.$ipset.tmp
        sed '/^add[[:space:]]/!d' $IPSET_DIR/$ipset > $temp
        $IPSET_BIN flush $ipset
        $IPSET_BIN restore -file $temp
        rm $temp
        logger -p local0.info "Flushed and restored $ipset ipset"
    else
        $IPSET_BIN restore -file $IPSET_DIR/$ipset
        logger -p local0.info "Restored $ipset ipset"
    fi
done

# Delete sets that are in memory, but don't have a save file.
for ipset in ${IPSET_SETS[@]}; do
    contains $ipset ${IPSET_FILES[@]}
    if [ $? -ne 0 ]; then
        $IPSET_BIN destroy $ipset
        logger -p local0.info "Destroyed $ipset ipset"
    fi
done
