---
- name: Packages
  apt:
      pkg:
          - exim4

- name: Configtype smarthost
  notify:
      - restart exim service
  lineinfile:
      dest: /etc/exim4/update-exim4.conf.conf
      regexp: "^dc_eximconfig_configtype="
      line: "dc_eximconfig_configtype='smarthost'"
  register: exim_configtype_smarthost
  when: "'localhost' not in admin_email"
  # Update

- name: Configtype local
  notify:
      - restart exim service
  lineinfile:
      dest: /etc/exim4/update-exim4.conf.conf
      regexp: "^dc_eximconfig_configtype="
      line: "dc_eximconfig_configtype='local'"
  register: exim_configtype_local
  when: "'localhost' in admin_email"
  # Update

- name: Smarthost
  notify:
      - restart exim service
  lineinfile:
      dest: /etc/exim4/update-exim4.conf.conf
      regexp: "^dc_smarthost="
      line: "dc_smarthost='{{ smtp_server }}::587'"
  when: smtp_server != ""
  register: exim_smarthost
  # Update

- name: Credentials
  notify:
      - restart exim service
  copy:
      dest: /etc/exim4/passwd.client
      content: "{{ smtp_server }}:{{ smtp_username }}:\
                {{ smtp_password }}"
      group: Debian-exim
      mode: 0640
  when:
      smtp_server != ""
      and smtp_username != ""
      and smtp_password != ""
  register: exim_credentials
  # Update

- name: Mailname
  notify:
      - restart exim service
  copy:
      content: "{{ hostname }}"
      dest: /etc/mailname
  when: admin_email != "root@localhost"

- name: Update
  command: update-exim4.conf
  when:
      exim_configtype_local is changed
      or exim_configtype_smarthost is changed
      or exim_smarthost is changed
      or exim_credentials is changed


# Handlers.

- name: Handlers
  meta: flush_handlers
