---

# OS.

- name: DebConf
  debconf:
      name: iptables-persistent
      question: "{{ item }}"
      value: "false"
      vtype: boolean
  with_items:
      - iptables-persistent/autosave_v4
      - iptables-persistent/autosave_v6

- name: Packages
  apt:
      pkg:
          - iptables-persistent


# Rules.

- name: IPv4 rules
  notify:
      - restart iptables service
  template:
      src: rules4
      dest: /etc/iptables/rules.v4
  when: not ssh_admin_only

- name: IPv6 rules
  notify:
      - restart iptables service
  template:
      src: rules6
      dest: /etc/iptables/rules.v6
  when: not ssh_admin_only

- name: IPv4 SSH rules
  notify:
      - restart iptables service
  template:
      src: rules4-admin
      dest: /etc/iptables/rules.v4
  when: ssh_admin_only

- name: IPv6 SSH rules
  notify:
      - restart iptables service
  template:
      src: rules6-admin
      dest: /etc/iptables/rules.v6
  when: ssh_admin_only

- name: Flush commands
  copy:
      src: flush
      dest: /etc/iptables/flush


# Handlers.

- name: Handlers
  meta: flush_handlers
