---

# OS.

- name: DebConf
  debconf:
      name: iptables-persistent
      question: "{{ item }}"
      value: "false"
      vtype: boolean
  with_items:
      - iptables-persistent/autosave_v4
      - iptables-persistent/autosave_v6

- name: Packages
  apt:
      pkg:
          - iptables-persistent


# Rules.

- name: IPv4 whitelist rules
  notify:
      - restart iptables service
  template:
      src: rules-whitelist.v4
      dest: /etc/iptables/rules.v4
  when: admin_whitelist

- name: IPv4 rules
  notify:
      - restart iptables service
  template:
      src: rules.v4
      dest: /etc/iptables/rules.v4
  when: not admin_whitelist

- name: IPv6 whitelist rules
  notify:
      - restart iptables service
  template:
      src: rules-whitelist.v6
      dest: /etc/iptables/rules.v6
  when: admin_whitelist

- name: IPv6 rules
  notify:
      - restart iptables service
  template:
      src: rules.v6
      dest: /etc/iptables/rules.v6
  when: not admin_whitelist

- name: Flush commands
  copy:
      src: flush
      dest: /etc/iptables/flush


# Handlers.

- name: Handlers
  meta: flush_handlers
