server {
    listen 80;
    listen [::]:80;
    server_name default_server;
    location / {
        try_files $uri @redirect;
    }
    location /.well-known {
        root /var/opt/acme-dir;
    }
    location @redirect {
        return 301 https://{{ hostname }}$request_uri;
    }
}
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 444;
}
