---

# OS.

- name: Packages
  apt:
      pkg:
          - git
          - ipset


# Sets.

- name: Directory
  file:
      path: /opt/firewall/ipset
      state: directory
      mode: 0700

- name: Repo
  git:
      repo: "{{ ipset_repo }}"
      dest: /opt/firewall/ipset
      version: "{{ ipset_version }}"
      force: true
  register: ipset_repo

- name: Notify
  notify:
      - run ipset service
  command: /bin/true
  when: ipset_repo.before == None

- name: Service
  copy:
      src: service
      dest: /etc/systemd/system/ipset.service
      mode: 0644

- name: Service status
  systemd:
      name: ipset.service
      enabled: true
      daemon-reload: true


# Handlers.

- name: Handlers
  meta: flush_handlers
